name: FastFurnace
version: '${version}'
main: net.azisaba.fastfurnace.FastFurnace
api-version: '1.15'
authors: [ Azisaba Network ]
description: 相対的時空間かまど
commands:
  fastfurnace:
    description: 相対的時空間かまどを付与します
    permission: fastfurnace.admin

permissions:
  fastfurnace.admin:
    description: 相対的時空間かまどを付与する権限
